### PR TITLE
fix/integration-tests

### LINKED ISSUE #254: Integration tests do not run locally
### Bug Description

I've attempted to run the integration tests on two different machines according to the repo's [documentation](https://github.com/canonical/wazuh-server-operator/blob/main/CONTRIBUTING.md).

In both cases, the tests quickly errored out and crashed. After manually identifying and fixing the first few errors, the tests continued to error out and crash.

They do seem to work via GitHub actions, so I will start troubleshooting by attempting to re-create the workflow as closely as possible and (once a successful configuration is found) update the docs.

### To Reproduce

Attempt to run the integration tests locally, following the procedure in the [documentation](https://github.com/canonical/wazuh-server-operator/blob/main/CONTRIBUTING.md)

### Environment

Starting from a [charm-dev](https://github.com/canonical/multipass-blueprints/blob/main/v1/charm-dev.yaml) VM and customizing according to the docs

### Relevant log output

```shell
NA; Multiple failure modes/logs
```

### Additional context

NA

### PR DESCRIPTION
**Pull request by niwamo**
Applicable spec: NA

### Overview

Fixes #254 

- Moves development setup and testing instructions from CONTRIBUTING.md to a separate how-to with significantly expanded instructions
- Several bugfixes in the integration tests:
   - wazuh-indexer is integrated with self-signed-certificates _before_ config_single_node_index is called, otherwise indexer never comes online
   - config_single_node_index waits for the indexer to create the password. Without a loop, the indexer never creates the password in time
   - asyncio used to cleanup pending tasks after controller disconnect (not strictly necessary but cleans up several dozen lines of error messages in pytest output)
   - opencti is now integrated/related with wazuh-server even on `--no-deploy` (previously caused error)
   - removed hard-coded, (usually) incorrect model name from get_ca_certificate
   - updated get_wazuh_ip to reference a "qualified" model name (i.e. `<controller>:<model>`) to prevent errors when a different controller is active/selected

### Rationale

Integration tests failed when running locally

### Juju Events Changes

NA

### Module Changes

NA

### Library Changes

NA

### Checklist

- [x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [x] The changes are compliant with [ISD054 - Managing Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [x] The documentation for charmhub is updated
- [x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
- [ ] The [changelog](../docs/changelog.md) is updated with user-relevant changes in the format of [keep a changelog v1.1.0](https://keepachangelog.com/en/1.1.0/)

### CODE REVIEW

File: tests/integration/config_single_node_index.sh [hunk 1]
```diff
@@ -21,7 +21,18 @@ if ! juju show-application wazuh-indexer &>/dev/null; then
...
 PASSWORD=$(for secret in $(juju secrets | tail +2 | awk '{print $1}'); do juju show-secret "$secret" --reveal; done | awk '/admin-password:/{print $2}')
+while [[ $PASSWORD == "" ]]; do
+	if [[ $num_sleeps -ge 30 ]]; then
+		echo "wazuh-indexer still not ready, exiting"
+		exit 1
+	fi
+	echo "wazuh-indexer not ready, waiting 30s"
+	num_sleeps=$(( num_sleeps + 1 ))
+	sleep 30
+	PASSWORD=$(for secret in $(juju secrets | tail +2 | awk '{print $1}'); do juju show-secret "$secret" --reveal; done | awk '/admin-password:/{print $2}')
```
[the remark this answers is not in the document]
Comment (niwamo) [reply tests/integration/config_single_node_index.sh]: done

File: tests/integration/conftest.py [hunk 2]
```diff
@@ -247,15 +261,15 @@ async def opencti_any_charm_fixture(
...
+        any_app: Application = model.applications[any_app_name]
+    else:
+        any_app: Application = await model.deploy(
+            "any-charm",
+            application_name=any_app_name,
+            channel="beta",
+            config={"src-overwrite": json.dumps(any_charm_src_overwrite), "python-packages": "PyJWT"},
+        )
+        await model.wait_for_idle(apps=[any_app_name], timeout=600)
+    await model.integrate(any_app.name, f"{application.name}:opencti-connector")
```
[the remark this answers is not in the document]
Comment (niwamo) [reply tests/integration/conftest.py:276]: By design (and depending on provided args), the OpenCTI charm is retained after a test run, while wazuh-server is destroyed. On subsequent runs intending to use the existing models, the existing OpenCTI charm and new wazuh-server charm never got related.

The wait for idle was added after observing that it takes the charms 30s to 2min to actually populate all the tested relation data.

The model.relate --> model.integrate change is simply because the old function is deprecated

File: docs/how-to/test-the-charm.md [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+pre-configured environments that can be used for linting and formatting code
+when you're preparing contributions to the charm:
+
+```bash
+tox run -e fmt        # update your code according to linting rules
+tox run -e lint       # code style
+tox run -e static     # other checks such as `bandit` for security issues.
+tox run -e unit       # unit tests
+tox                   # runs 'format', 'lint', 'static' and 'unit' environments
+```
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:151]: To avoid the Vale warning, I recommend using the following formatting (see [CONTRIBUTING.md in platform-engineering-charm-template](https://github.com/canonical/platform-engineering-charm-template/blob/main/CONTRIBUTING.md?plain=1)):
````suggestion
* ``tox``: Executes all of the basic checks and tests (``lint``, ``unit``, ``static``, and ``format``).
* ``tox run -e fmt``: Update your code according to linting rules.
* ``tox run -e lint``: Runs a range of static code analysis to check the code.
* ``tox run -e static``: Runs other checks such as ``bandit`` for security issues.
* ``tox run -e unit``: Runs unit tests.
````

File: docs/how-to/test-the-charm.md [hunk 4]
```diff
@@ -0,0 +1,257 @@
...
+```bash
+cd ~/wazuh-server-operator
+charmcraft pack
+```
+
+#### Optional - build the rock
+
+If you have not made any changes to the rock, you do not need to rebuild it.
+
+The Github integration test workflow builds and uploads the rock to `ghcr.io`
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:172]:
```suggestion
The GitHub integration test workflow builds and uploads the rock to `ghcr.io`
```

File: docs/how-to/test-the-charm.md [hunk 5]
```diff
@@ -0,0 +1,257 @@
...
+for its own tests. If you haven't changed the rock since the last Github action
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:173]:
```suggestion
for its own tests. If you haven't changed the rock since the last GitHub action
```

File: docs/how-to/test-the-charm.md [hunk 6]
```diff
@@ -0,0 +1,257 @@
...
+
+```bash
+tox run -e integration -- \
+    --charm-file=wazuh-server_ubuntu-22.04-amd64.charm \
+    --wazuh-server-image $IMAGE_URL \
+    --single-node-indexer \
+    --controller k8s --model test-wazuh
+```
+
+##### To reuse environments
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:235]:
```suggestion
##### Reuse environments
```
Nitpick

**Review by erinecon — COMMENTED** [review]
Thanks so much for your documentation contributions!

File: CONTRIBUTING.md [hunk 7]
```diff
@@ -1,36 +1,24 @@
...
-
-Add the following configuration in `/etc/docker/daemon.json`. Change `ubuntu` to your host name:
-```
-{ "insecure-registries": ["ubuntu.local:5000"] }
-```
+This document explains the processes and practices recommended for contributing enhancements to the Wazuh server charm.
+
+## Overview
+
+- Generally, before developing enhancements to this charm, you should consider [opening an issue
```
Comment (seb4stien) [inline CONTRIBUTING.md:7]: @niwamo what config did you use to limit lines lenght in markdown files?
I'm not sure we have any recommendations in the team about it in the team yet, do we @erinecon ? That may be something to standardize.

Comment (erinecon) [reply CONTRIBUTING.md:7]: We currently don't have any recommendation in the team, but it has come up before and I do have a to-do list item to implement a recommendation. 

Personally I think that line-wrapping is a good practice that we should implement. We can discuss in the team about the exact number we want to recommend :)

File: docs/how-to/test-the-charm.md [hunk 8]
```diff
@@ -0,0 +1,259 @@
...
+systemctl restart docker
+```
+
+#### Install skopeo
+
+```bash
+apt install -y skopeo
+```
+
+## Linting, static testing, and unit testing
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:143]:
```suggestion
## Testing
```
Nitpick, just to be more concise

File: docs/how-to/test-the-charm.md [hunk 9]
```diff
@@ -0,0 +1,259 @@
...
+1. Running the tests
+
+#### Build the charm
+
+```bash
+cd ~/wazuh-server-operator
+charmcraft pack
+```
+
+#### Optional - build the rock
```
Comment (erinecon) [inline docs/how-to/test-the-charm.md:170]:
```suggestion
#### (Optional) Build the rock
```
Nitpick, just to be consistent with the previous `(Optional)` header style

**Review by erinecon — APPROVED** [review]
Good point about me needing to approve -- thanks!
